### ISSUE TITLE
chan 添加缓冲

### ISSUE THREAD

**Issue by ruanhanqin** [PualrDwade/go-douban-spider#1]
urls := make(chan string)
results := make(chan Result)
resources := make(chan Resource)

这里的chan建议添加缓冲，不然会卡住

urls := make(chan string, 10000)
results := make(chan Result, 10000)
resources := make(chan Resource, 10000)

**Comment by PualrDwade** [comment]
你说的没错,不过由于爬虫的限制还是网络带宽,所以添加了效果也不明显O(∩_∩)O
